---
- name: Ensure system is up to date
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Configure Minecraft application user
  ansible.builtin.import_tasks: tasks/mc_user.yml

- name: Install and configure Temurin 17 OpenJDK
  ansible.builtin.import_tasks: tasks/open_jdk.yml

- name: Install Minecraft server
  ansible.builtin.import_tasks: tasks/mc_install.yml

- name: Configure the Minecraft service via Supervisor
  ansible.builtin.import_tasks: tasks/mc_service.yml
  when: manage_service

- name: Configure local server backups
  ansible.builtin.import_tasks: tasks/server_backup.yml
  when: enable_backups
