---
- name: Create {{ install_dir }}
  ansible.builtin.file:
    path: "{{ install_dir }}"
    state: directory
    group: "{{ mc_user }}"
    owner: "{{ mc_user }}"
    mode: '0755'

- name: Get Minecraft JAR
  ansible.builtin.get_url:
    url: https://launcher.mojang.com/v1/objects/c8f83c5655308435b3dcf03c06d9fe8740a77469/server.jar
    dest: "{{ install_dir }}/minecraft_server.1.18.2.jar"
    mode: '0644'

- name: Accept Minecraft EULA
  ansible.builtin.lineinfile:
    path: "{{ install_dir }}/eula.txt"
    line: eula=true
    state: present
    create: true
    mode: '0644'

- name: Configure server properties
  ansible.builtin.template:
    src: server.properties.j2
    dest: "{{ install_dir }}/server.properties"
    mode: '0644'
