---
- name: Configure OpenSSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop:
    - {key: "Port", value: "{{ ssh_port }}"}
    - {key: "PermitRootLogin", value: "{{ permit_root_login }}"}
    - {key: "PubkeyAuthentication", value: "{{ pubkey_authentication }}"}
    - {key: "PasswordAuthentication", value: "{{ password_authentication }}"}
    - {key: "PermitEmptyPasswords", value: "{{ permit_empty_passwords }}"}
    - {key: "ChallengeResponseAuthentication", value: "{{ challenge_response_authentication }}"}
    - {key: "UsePAM", value: "{{ use_pam }}"}
    - {key: "X11Forwarding", value: "{{ x11_forwarding }}"}
    - {key: "PrintMotd", value: "{{ print_motd }}"}
    - {key: "AcceptEnv", value: "{{ accept_env }}"}
    - {key: "Subsystem", value: "{{ subsystem }}"}
  notify:
    - restart sshd
