---
- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny

- name: Configure SSH and server ports
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "{{ item }}"
  with_items:
    - " {{ server_port }}"
    - " {{ ssh_port }}"
